Spinner n notification
Ivanekrasov/itmo-react-practice pull request #7
Opened 2020-02-23 21:46 UTC by AlexandraSusloparova

2020-02-26 19:52 UTC, Fr0stmourne commented on src/js/App/App.js
> -import './App.scss';
please place all the imports in the order 'libs - empty line - project imports - empty line -  style imports'

2020-02-28 09:30 UTC, Ivanekrasov requested changes

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/Alert/Alert.js
> +}
Use arrow function please and return it on the same line

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/Drawer/Drawer.js
>      const flags = Object.fromEntries(apiInfo.map(key => [key.rover, false]));
U'll got an error here in case of rejected promise

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/Drawer/Drawer.js
> +    const notificationText = 'Error. Please contact system administrator';
This will be redefined every time component renders. Make it class property e.g.

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/Drawer/Drawer.js
> +          autoHideDuration={6000}
Move to constant value please

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/ImageCard/ImageCard.js
> +  const [loaded, setLoadingStatus] = useState(false);
wow hooks :D

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/NasaTable/NasaTable.js
> +      notification: false,
Rename it to look like a boolean value please. E.g. isNotificationShown or shouldShowNotification

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/NasaTable/NasaTable.js
>      this.setDataToShow({ rowsPerPage, page, data });
Maybe it'll be better to add some initial value to exclude undefined in state?

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/NasaTable/NasaTable.js
> +    const notificationText = 'Error. Please contact system administrator';
To a const please

2020-02-28 09:30 UTC, Ivanekrasov commented on src/js/NasaTable/NasaTable.js
> +          autoHideDuration={6000}
This too

2020-02-28 17:16 UTC, AlexandraSusloparova commented on src/js/ImageCard/ImageCard.js
> +  const [loaded, setLoadingStatus] = useState(false);
ty ty)

2020-03-02 18:56 UTC, merged